---
title: "ggplot"
output: html_document
date: "2024-06-11"
---


```{r}
library(tidyverse)
library(dplyr)
library(tidyr)
library(stringr)

library(ggplot2)
library(ggrepel)
library(patchwork)
```


# Building a plot
```{r}
data("iris")
head(iris)

ggplot(data=iris)
ggplot(data=iris)+
  geom_point(mapping=aes(x=Petal.Length,y=Petal.Width))


ggplot(data=iris,mapping=aes(x=Petal.Length,y=Petal.Width))+
  geom_point()+
  geom_smooth(method="lm")

ggplot(data=iris,mapping=aes(x=Petal.Length,y=Petal.Width,color=Species))+
  geom_point()+
  geom_smooth(method="lm")

ggplot(data=iris,mapping=aes(x=Petal.Length,y=Petal.Width))+
  geom_point(aes(color=Species))+
  geom_smooth(method="lm")

ggplot(data=iris,mapping=aes(x=Petal.Length,y=Petal.Width))+
  geom_point(aes(color=Sepal.Width))+
  geom_smooth(method="lm")

?geom_point()

newtheme <- theme(
    axis.title=element_text(color="Blue",face="bold"),
    plot.title=element_text(color="Green",face="bold"),
    plot.subtitle=element_text(color="Pink"),
    panel.grid=element_blank())

ggplot(data=iris,mapping=aes(x=Petal.Length,y=Petal.Width))+
  geom_point(aes(color=Sepal.Width))+
  geom_smooth(method="lm")+
  scale_color_continuous(name="New Legend Title")+
  scale_x_continuous(breaks = 1:8)+
  labs(title="This Is A Title",subtitle="This is a subtitle",x=" Petal Length", 
       y="Petal Width", caption="This is a little caption.") + 
  facet_wrap(~Species) +
  theme_bw() +
  newtheme


ggplot(data=iris,mapping=aes(x=Petal.Length,y=Petal.Width))+
  geom_point(aes(color=Species,size=Sepal.Width))+
  guides(size=guide_legend(nrow=2,byrow=T),
         color=guide_legend(nrow=3,byrow=T))+
  theme(legend.position = "top",
        legend.justification = "right")

ggplot(data=iris,mapping=aes(x=Petal.Length,y=Petal.Width))+
  geom_point(aes(color=Species))+
  geom_text(aes(label=Species,hjust=0),nudge_x=0.5,size=3)+

ggplot(data=iris,mapping=aes(x=Petal.Length,y=Petal.Width))+
  geom_point(aes(color=Species))+
  geom_label(aes(label=Species,hjust=0),nudge_x=0.5,size=3)

library(ggrepel)
ggplot(data=iris,mapping=aes(x=Petal.Length,y=Petal.Width))+
  geom_point(aes(color=Species))+
  geom_text_repel(aes(label=Species),size=3)

```
# Economist Scatterplot
```{r}
ec <- read.csv("C:/Users/tobia/Desktop/RaukR/data_economist.csv",header=T)
head(ec)
str(ec)
levels(ec$Region)
ec$Region <- factor(ec$Region,levels = c("EU W. Europe",
                                "Americas",
                                "Asia Pacific",
                                "East EU Cemt Asia",
                                "MENA",
                                "SSA"),
                     labels = c("OECD",
                                "Americas",
                                "Asia &\nOceania",
                                "Central &\nEastern Europe",
                                "Middle East &\nNorth Africa",
                                "Sub-Saharan\nAfrica"))
```

```{r}

labels <- c("Congo","Afghanistan","Sudan","Myanmar","Iraq","Venezuela","Russia","Argentina","Brazil","Italy","South Africa","Cape Verde","Bhutan","Botswana","Britian","New Zealand","Greece","China","India","Rwanda","Spain","France","United States","Japan","Norway","Singapore","Barbados","Germany")

geom_text(data=subset(ec,Country %in% labels),aes(label=Country),color="black")
ggplot(ec, aes(x= CPI, y= HDI, color = Region)) + 
  geom_smooth(aes(fill="red"), method = "lm", formula=y~poly(x,2),se=F,size=0.6,color="red") +
  geom_point(shape=21,size=3,stroke=0.8,fill="white") +
  geom_text_repel(data=subset(ec,Country %in% labels),aes(label=Country),color="black",box.padding=unit(1,'lines'),segment.size=0.25,
                       size=3, family = "Gidole") + 
  scale_x_continuous(name="Corruption Perceptions Index, 2011 (10=least corrupt)",
                          breaks=1:10,limits=c(1,10))+
      scale_y_continuous(name="Human Development Index, 2011 (1=best)",
                         breaks=seq(from=0,to=1,by=0.1),limits=c(0.2,1)) +
  scale_color_manual(values=c("#23576E","#099FDB","#29B00E", "#208F84","#F55840","#924F3E")) +
  scale_fill_manual(name="trend",values="red",labels=expression(paste(R^2,"=52%"))) +
  labs(title="Corruption and human development",
            caption="Sources: Transparency International; UN Human Development Report") +
 guides(color=guide_legend(nrow=1))+
       theme_bw(base_family="Gidole")+
       theme(legend.position="top") +

  theme(panel.grid.minor=element_blank(),
          panel.grid.major.x=element_blank(),
          panel.background=element_blank(),
          panel.border=element_blank(),
          legend.title=element_blank(),
          axis.title=element_text(face="italic"),
          axis.ticks.y=element_blank(),
          axis.ticks.x=element_line(color="grey60"),
          plot.title=element_text(face="bold"),
          plot.caption=element_text(hjust=0,size=8))

  
```
#WSJ Heatmap
```{r}
me <- read.csv("C:/Users/tobia/Desktop/RaukR/data_wsj.csv",header=T, stringsAsFactors=F,skip=2)

me1 <- me %>% gather(key=state,value=value,-YEAR,-WEEK)
head(me1)

me2 <- me1 %>% mutate(value=str_replace(value,"^-$",NA_character_),
                      value=as.numeric(value))
head(me2)

# custom summing function
fun1 <- function(x) ifelse(all(is.na(x)),NA,sum(x,na.rm=TRUE))

# read data
me3 <- read.csv("C:/Users/tobia/Desktop/RaukR/data_wsj.csv",header=T,
               stringsAsFactors=F,skip=2) %>%
        gather(key=state,value=value,-YEAR,-WEEK) %>%
        mutate(value=str_replace(value,"^-$",NA_character_),
                            value=as.numeric(value)) %>%
        group_by(YEAR,state) %>% 
                      summarise(total=fun1(value)) %>%
                      mutate(state=str_replace_all(state,"[.]"," "),
                             state=str_to_title(state))

colnames(me3) <- tolower(colnames(me3))

# custom colors
cols <- c("#e7f0fa","#c9e2f6","#95cbee","#0099dc","#4ab04a", "#ffd73e","#eec73a","#e29421","#f05336","#ce472e")

# plotting
p <- ggplot(me3,aes(x=year,y=reorder(state,desc(state)),fill=total))+
      geom_tile(color="white",size=0.25)+
      scale_y_discrete(expand=c(0,0))+
      scale_x_continuous(expand=c(0,0),breaks=seq(1930,2010,by=10))+
      scale_fill_gradientn(colors=cols,na.value="grey95",
                           limits=c(0,4000),
                           values=c(0,0.01,0.02,0.03,0.09,0.1,0.15,0.25,0.4,0.5,1),
                           labels=c("0k","1k","2k","3k","4k"),
                           guide=guide_colourbar(ticks=T,nbin=50,
                                               barheight=.5,label=T, 
                                               barwidth=10))+
      labs(x="",y="",fill="",title="Measles")+
      coord_fixed()+
      geom_segment(x=1963,xend=1963,y=0,yend=51.5,size=.9) +
      annotate("text",label="Vaccine introduced",x=1963,y=53, 
               vjust=1,hjust=0,size=I(3),family="Gidole")+
      theme_minimal(base_family="Gidole")+
      theme(legend.position=c(.5,-.13),
        legend.direction="horizontal",
        legend.text=element_text(color="grey20"),
        plot.margin=grid::unit(c(.5,0,1.5,0),"cm"),
        axis.text.y=element_text(size=6,hjust=1,vjust=0.5),
        axis.text.x=element_text(size=8),
        axis.ticks.y=element_blank(),
        panel.grid=element_blank(),
        title=element_text(hjust=-.07,vjust=1),
        panel.grid=element_blank())
```

